checks:
    go: true
build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            environment:
                go:
                    version: go1.12.9
            tests:
                override:
                    - go-scrutinizer-run
                    - govet-run
                    - golint-run
        tests:
            environment:
                go:
                    version: go1.12.9